ur3_config:
  ready: [0.0,-0.785,0.0,-2.355,0.0,0.785]
# task_msg:
#   F_pose: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
#   joint_goal: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
#   joint_id: "0123456"
#   follow_duration: 0.0

# motion_step:
#   stop: &stop
#     - movetype: 0
#     - barm: true
#     - bgrasp: true
#     - gripper_command: false


#   ready: &ready
#     - move_type: 6
#     - barm: true
#     - bgrasp: true
#     - joint_goal: [0.0,-0.785,0.0,-2.355,0.0,1.57,0.785]
#     - gripper_command: false
  
# task_step:  

#   task_type: 0
#   step_num: 4
#   step_list: [
#     - *ready
#     - 
#   ]

#   movetype2: 4
#   grasptype2: 1
#   duration2: 2
#   qtarget2: [0.0,0.785,0.0,-2.0,0.0,2.8,0.785]
#   dxyzrpy2: [0.0,0.2,-0.1,0.0,0.0,1.0]

#   # movetype2: 1
#   # grasptype2: 1
#   # duration2: 0.5
#   # qtarget2: [0.0,0.785,0.0,-2.0,0.0,2.8,0.785]

#   movetype3: 1
#   grasptype3: 1
#   duration3: 2
#   qtarget3: [0.0,-0.785,0.0,-2.855,0.0,2.8,0.785]
#   dxyzrpy3: [0.0,0.0,0.0,0.0,0.0,0.0]

#   movetype4: 1
#   grasptype4: 1
#   duration4: 2
#   qtarget4: [1.0,0,0.0,-2.355,0.0,2.8,0.785]
#   dxyzrpy4: [0.0,0.0,0.0,0.0,0.0,0.0]

#   movetype5: 1
#   grasptype5: 0
#   duration5: 2
#   qtarget5: [1.0,0.785,0.0,-2.0,0.0,2.8,0.785]
#   dxyzrpy5: [0.0,0.0,0.0,0.0,0.0,0.0]

#   movetype6: 1
#   grasptype6: 0
#   duration6: 2
#   qtarget6: [1.0,0.0,0.0,-2.355,0.0,2.8,0.785]
#   dxyzrpy6: [0.0,0.0,0.0,0.0,0.0,0.0]
